description: The official Project27 Solutions site. Designing and diffusing solutions in partnership with researchers and businesses.
collections:
  volunteering:
    output: true
  about:
    output: true
sass: 
   sass_dir: assets/css
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
# baseurl: /project27
baseurl:
excerpt_separator: <!-- excerpt-end -->
organisation: Project27 Consultancy Group
org: PCG
brand: Project27 Solutions
motto: Solutions that work